name: udd-update-dependencies

on:
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.20.2
      - name: Update dependencies
        run: |
          deno run -A https://deno.land/x/udd/main.ts slack.json import_map.json 
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: pr
        with:
          commit-message: "Update dependencies"
          title: Update dependencies
          body: >
            Dependencies updated by [udd](https://github.com/hayd/deno-udd).
          branch: pre-release
          author: GitHub <noreply@github.com>
          delete-branch: true
      - name: Retrieve commit sha
        id: commit
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Set commit status with pending
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: "Basic tests"
          state: "pending"
          sha: ${{ steps.commit.outputs.sha }}
      - name: Basic tests
        id: test
        continue-on-error: true
        run: |
          deno test --allow-read --allow-write
      - name: Set commit status with outcome
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: "Basic tests"
          description: "To run other CI actions close/reopen this PR"
          state: ${{ steps.test.outcome }}
          sha: ${{ steps.commit.outputs.sha }}
      - name: Retrieve PR number
        id: pr_num
        run: echo "::notice ::PR_NUM=${{ env.PULL_REQUEST_NUMBER }}"
